// ============================================================
//  seed.js
//  Script de population de la base de données
//  Importe les 30 talents du mockData.js dans MongoDB
//
//  Usage : node seed.js
//  ⚠️  À exécuter UNE SEULE FOIS pour initialiser la base
// ============================================================

require('dotenv').config();
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const connectDB = require('./config/db');
const User = require('./models/User');
const Talent = require('./models/Talent');

// ── Données des 30 talents (repris du mockData.js frontend) ──
const talentsSeed = [
  {
    nom: 'Kamga Jean-Pierre',
    metier: 'Développeur Web Frontend',
    categorie: 'Tech & Digital',
    avatar: 'https://i.pravatar.cc/150?img=11',
    competences: [
      { nom: 'Vue.js', niveau: 92 },
      { nom: 'Tailwind CSS', niveau: 88 },
      { nom: 'JavaScript', niveau: 85 },
      { nom: 'Figma', niveau: 70 },
    ],
    ville: 'Douala',
    quartier: 'Akwa',
    disponibilite: 'disponible',
    bio: "Développeur frontend passionné avec 3 ans d'expérience. Je transforme les maquettes en interfaces web fluides et modernes.",
    portfolio: [
      'https://picsum.photos/seed/port1/400/300',
      'https://picsum.photos/seed/port2/400/300',
    ],
    telephone: '+237 699 123 456',
    email: 'kamga.jp@gmail.com',
    dateInscription: '2024-01-15',
    vues: 342,
    note: 4.8,
    avis: 27,
    tarifJour: 25000,
  },
  {
    nom: 'Ngo Mbassi Christelle',
    metier: 'UI/UX Designer',
    categorie: 'Tech & Digital',
    avatar: 'https://i.pravatar.cc/150?img=47',
    competences: [
      { nom: 'Figma', niveau: 95 },
      { nom: 'Adobe XD', niveau: 88 },
      { nom: 'Illustrator', niveau: 80 },
      { nom: 'Prototypage', niveau: 90 },
    ],
    ville: 'Yaoundé',
    quartier: 'Bastos',
    disponibilite: 'disponible',
    bio: "Designer UX/UI avec 4 ans d'expérience dans la création d'interfaces centrées utilisateur.",
    portfolio: ['https://picsum.photos/seed/port4/400/300'],
    telephone: '+237 677 234 567',
    email: 'christelle.ngo@outlook.com',
    dateInscription: '2024-01-22',
    vues: 289,
    note: 4.9,
    avis: 34,
    tarifJour: 30000,
  },
  {
    nom: 'Fopa Éric',
    metier: 'Développeur Mobile (Flutter)',
    categorie: 'Tech & Digital',
    avatar: 'https://i.pravatar.cc/150?img=15',
    competences: [
      { nom: 'Flutter', niveau: 90 },
      { nom: 'Dart', niveau: 88 },
      { nom: 'Firebase', niveau: 82 },
      { nom: 'REST API', niveau: 75 },
    ],
    ville: 'Douala',
    quartier: 'Bonanjo',
    disponibilite: 'occupé',
    bio: "Développeur mobile spécialisé Flutter. J'ai publié 3 applications sur le Play Store.",
    portfolio: ['https://picsum.photos/seed/port6/400/300'],
    telephone: '+237 655 345 678',
    email: 'fopa.eric@gmail.com',
    dateInscription: '2024-02-03',
    vues: 198,
    note: 4.7,
    avis: 19,
    tarifJour: 35000,
  },
  {
    nom: 'Talla Bertrand',
    metier: 'Community Manager',
    categorie: 'Tech & Digital',
    avatar: 'https://i.pravatar.cc/150?img=18',
    competences: [
      { nom: 'Gestion réseaux', niveau: 92 },
      { nom: 'Création contenu', niveau: 85 },
      { nom: 'Canva', niveau: 88 },
      { nom: 'Analytics', niveau: 72 },
    ],
    ville: 'Bafoussam',
    quartier: 'Tamdja',
    disponibilite: 'partiellement disponible',
    bio: "Community manager avec 2 ans d'expérience. Je gère les pages de 8 PME camerounaises.",
    portfolio: [],
    telephone: '+237 690 456 789',
    email: 'talla.b@gmail.com',
    dateInscription: '2024-02-14',
    vues: 156,
    note: 4.5,
    avis: 14,
    tarifJour: 15000,
  },
  {
    nom: 'Mbarga Sophie',
    metier: 'Photographe Professionnelle',
    categorie: 'Créatif & Art',
    avatar: 'https://i.pravatar.cc/150?img=48',
    competences: [
      { nom: 'Portrait', niveau: 95 },
      { nom: 'Événementiel', niveau: 90 },
      { nom: 'Lightroom', niveau: 88 },
      { nom: 'Photoshop', niveau: 82 },
    ],
    ville: 'Douala',
    quartier: 'Bonapriso',
    disponibilite: 'disponible',
    bio: 'Photographe professionnelle spécialisée dans les portraits et les événements.',
    portfolio: [
      'https://picsum.photos/seed/port9/400/300',
      'https://picsum.photos/seed/port10/400/300',
    ],
    telephone: '+237 677 567 890',
    email: 'sophie.mbarga@gmail.com',
    dateInscription: '2024-02-20',
    vues: 421,
    note: 4.9,
    avis: 52,
    tarifJour: 50000,
  },
  {
    nom: 'Tchoumba Rodrigue',
    metier: 'Vidéaste & Monteur',
    categorie: 'Créatif & Art',
    avatar: 'https://i.pravatar.cc/150?img=22',
    competences: [
      { nom: 'Premiere Pro', niveau: 92 },
      { nom: 'After Effects', niveau: 80 },
      { nom: 'Prise de vue', niveau: 88 },
      { nom: 'Motion design', niveau: 75 },
    ],
    ville: 'Yaoundé',
    quartier: 'Mvan',
    disponibilite: 'disponible',
    bio: 'Vidéaste passionné. Je réalise des clips musicaux, des publicités et des documentaires courts.',
    portfolio: ['https://picsum.photos/seed/port12/400/300'],
    telephone: '+237 699 678 901',
    email: 'rodrigue.tchoumba@gmail.com',
    dateInscription: '2024-03-01',
    vues: 267,
    note: 4.6,
    avis: 23,
    tarifJour: 40000,
  },
  {
    nom: 'Feudjio Larissa',
    metier: 'Illustratrice & Graphiste',
    categorie: 'Créatif & Art',
    avatar: 'https://i.pravatar.cc/150?img=44',
    competences: [
      { nom: 'Illustrator', niveau: 94 },
      { nom: 'Photoshop', niveau: 88 },
      { nom: 'Illustration', niveau: 96 },
      { nom: 'Identité visuelle', niveau: 85 },
    ],
    ville: 'Douala',
    quartier: 'Deido',
    disponibilite: 'partiellement disponible',
    bio: 'Graphiste et illustratrice. Je crée des identités visuelles mémorables.',
    portfolio: [
      'https://picsum.photos/seed/port14/400/300',
      'https://picsum.photos/seed/port15/400/300',
    ],
    telephone: '+237 655 789 012',
    email: 'feudjio.larissa@gmail.com',
    dateInscription: '2024-03-10',
    vues: 380,
    note: 5,
    avis: 41,
    tarifJour: 28000,
  },
  {
    nom: 'Ngono Parfait',
    metier: 'Menuisier Ébéniste',
    categorie: 'Artisanat & BTP',
    avatar: 'https://i.pravatar.cc/150?img=30',
    competences: [
      { nom: 'Menuiserie', niveau: 95 },
      { nom: 'Ébénisterie', niveau: 90 },
      { nom: 'Placage', niveau: 85 },
      { nom: 'Vernissage', niveau: 80 },
    ],
    ville: 'Bafoussam',
    quartier: 'Djeleng',
    disponibilite: 'disponible',
    bio: "Menuisier ébéniste avec 8 ans d'expérience. Je fabrique des meubles sur mesure.",
    portfolio: ['https://picsum.photos/seed/port17/400/300'],
    telephone: '+237 677 890 123',
    email: 'ngono.parfait@gmail.com',
    dateInscription: '2024-03-18',
    vues: 203,
    note: 4.7,
    avis: 31,
    tarifJour: 20000,
  },
  {
    nom: 'Djomo Clément',
    metier: 'Électricien Bâtiment',
    categorie: 'Artisanat & BTP',
    avatar: 'https://i.pravatar.cc/150?img=33',
    competences: [
      { nom: 'Installation élec.', niveau: 93 },
      { nom: 'Dépannage', niveau: 88 },
      { nom: 'Câblage réseau', niveau: 75 },
      { nom: 'Solaire', niveau: 70 },
    ],
    ville: 'Douala',
    quartier: 'Makepe',
    disponibilite: 'disponible',
    bio: "Électricien certifié avec 6 ans d'expérience.",
    portfolio: [],
    telephone: '+237 699 901 234',
    email: 'djomo.clement@gmail.com',
    dateInscription: '2024-04-02',
    vues: 178,
    note: 4.6,
    avis: 22,
    tarifJour: 18000,
  },
  {
    nom: 'Assanga Bruno',
    metier: 'Maçon & Carreleur',
    categorie: 'Artisanat & BTP',
    avatar: 'https://i.pravatar.cc/150?img=35',
    competences: [
      { nom: 'Maçonnerie', niveau: 92 },
      { nom: 'Carrelage', niveau: 90 },
      { nom: 'Enduit', niveau: 85 },
      { nom: 'Béton armé', niveau: 78 },
    ],
    ville: 'Yaoundé',
    quartier: 'Nkoldongo',
    disponibilite: 'occupé',
    bio: 'Maçon professionnel avec 10 ans de métier.',
    portfolio: ['https://picsum.photos/seed/port20/400/300'],
    telephone: '+237 655 012 345',
    email: 'assanga.bruno@gmail.com',
    dateInscription: '2024-04-10',
    vues: 145,
    note: 4.4,
    avis: 18,
    tarifJour: 15000,
  },
  {
    nom: 'Nkemdirim Aïcha',
    metier: 'Répétitrice (Maths & Physique)',
    categorie: 'Éducation & Formation',
    avatar: 'https://i.pravatar.cc/150?img=49',
    competences: [
      { nom: 'Mathématiques', niveau: 96 },
      { nom: 'Physique', niveau: 92 },
      { nom: 'Chimie', niveau: 85 },
      { nom: 'Pédagogie', niveau: 90 },
    ],
    ville: 'Yaoundé',
    quartier: 'Essos',
    disponibilite: 'disponible',
    bio: 'Ingénieure de formation, je donne des cours particuliers de maths et physique.',
    portfolio: [],
    telephone: '+237 677 123 456',
    email: 'aicha.nkemdirim@gmail.com',
    dateInscription: '2024-04-20',
    vues: 312,
    note: 4.9,
    avis: 45,
    tarifJour: 5000,
  },
  {
    nom: 'Kouam Pascal',
    metier: 'Formateur Bureautique & Informatique',
    categorie: 'Éducation & Formation',
    avatar: 'https://i.pravatar.cc/150?img=12',
    competences: [
      { nom: 'MS Office', niveau: 95 },
      { nom: 'Formation', niveau: 88 },
      { nom: 'Comptabilité', niveau: 80 },
      { nom: 'Initiation PC', niveau: 92 },
    ],
    ville: 'Bafoussam',
    quartier: 'Kamkop',
    disponibilite: 'partiellement disponible',
    bio: "Formateur en bureautique avec 5 ans d'expérience.",
    portfolio: [],
    telephone: '+237 690 234 567',
    email: 'kouam.pascal@gmail.com',
    dateInscription: '2024-05-05',
    vues: 189,
    note: 4.7,
    avis: 28,
    tarifJour: 8000,
  },
  {
    nom: 'Eyenga Clarisse',
    metier: 'Traiteur & Chef Cuisinier',
    categorie: 'Services & Lifestyle',
    avatar: 'https://i.pravatar.cc/150?img=46',
    competences: [
      { nom: 'Cuisine camerounaise', niveau: 98 },
      { nom: 'Pâtisserie', niveau: 88 },
      { nom: 'Buffets événementiels', niveau: 92 },
      { nom: 'Cuisine internationale', niveau: 75 },
    ],
    ville: 'Douala',
    quartier: 'Bali',
    disponibilite: 'disponible',
    bio: "Chef traiteur avec 7 ans d'expérience. Spécialité : ndolé, poulet DG, okok.",
    portfolio: ['https://picsum.photos/seed/port22/400/300'],
    telephone: '+237 655 345 678',
    email: 'eyenga.clarisse@gmail.com',
    dateInscription: '2024-05-12',
    vues: 276,
    note: 4.8,
    avis: 39,
    tarifJour: 60000,
  },
  {
    nom: 'Mbianda Rachel',
    metier: 'Coiffeuse & Styliste Capillaire',
    categorie: 'Services & Lifestyle',
    avatar: 'https://i.pravatar.cc/150?img=43',
    competences: [
      { nom: 'Tresses africaines', niveau: 95 },
      { nom: 'Lissage & défrisage', niveau: 90 },
      { nom: 'Coloration', niveau: 85 },
      { nom: 'Soins capillaires', niveau: 92 },
    ],
    ville: 'Douala',
    quartier: 'Ndokoti',
    disponibilite: 'partiellement disponible',
    bio: 'Coiffeuse professionnelle avec 5 ans de salon.',
    portfolio: ['https://picsum.photos/seed/port24/400/300'],
    telephone: '+237 699 456 789',
    email: 'mbianda.rachel@gmail.com',
    dateInscription: '2024-05-20',
    vues: 231,
    note: 4.6,
    avis: 33,
    tarifJour: 10000,
  },
  {
    nom: 'Ngambi Joséphine',
    metier: 'Couturière & Styliste Mode',
    categorie: 'Services & Lifestyle',
    avatar: 'https://i.pravatar.cc/150?img=41',
    competences: [
      { nom: 'Couture sur mesure', niveau: 96 },
      { nom: 'Tissus africains', niveau: 94 },
      { nom: 'Mode événementielle', niveau: 90 },
      { nom: 'Patronage', niveau: 85 },
    ],
    ville: 'Yaoundé',
    quartier: 'Biyem-Assi',
    disponibilite: 'disponible',
    bio: "Styliste-couturière avec 6 ans d'expérience alliant le wax africain aux coupes contemporaines.",
    portfolio: [
      'https://picsum.photos/seed/port25/400/300',
      'https://picsum.photos/seed/port26/400/300',
    ],
    telephone: '+237 677 567 890',
    email: 'ngambi.jo@gmail.com',
    dateInscription: '2024-06-01',
    vues: 318,
    note: 4.9,
    avis: 47,
    tarifJour: 15000,
  },
  {
    nom: 'Owono Marcel',
    metier: 'Chauffeur Professionnel',
    categorie: 'Transport & Logistique',
    avatar: 'https://i.pravatar.cc/150?img=16',
    competences: [
      { nom: 'Conduite VIP', niveau: 92 },
      { nom: 'Connaissance routes', niveau: 95 },
      { nom: 'Véhicules lourds', niveau: 80 },
      { nom: 'Conduite préventive', niveau: 88 },
    ],
    ville: 'Douala',
    quartier: 'Logpom',
    disponibilite: 'disponible',
    bio: "Chauffeur professionnel avec permis B, C et D. 8 ans d'expérience.",
    portfolio: [],
    telephone: '+237 690 678 901',
    email: 'owono.marcel@gmail.com',
    dateInscription: '2024-06-10',
    vues: 134,
    note: 4.5,
    avis: 16,
    tarifJour: 12000,
  },
  {
    nom: 'Djoumessi Wilfried',
    metier: 'Développeur Backend (Node.js)',
    categorie: 'Tech & Digital',
    avatar: 'https://i.pravatar.cc/150?img=20',
    competences: [
      { nom: 'Node.js', niveau: 90 },
      { nom: 'MongoDB', niveau: 85 },
      { nom: 'Express.js', niveau: 88 },
      { nom: 'Docker', niveau: 72 },
    ],
    ville: 'Douala',
    quartier: 'Kotto',
    disponibilite: 'partiellement disponible',
    bio: "Développeur backend Node.js avec 4 ans d'expérience.",
    portfolio: ['https://picsum.photos/seed/port28/400/300'],
    telephone: '+237 655 789 012',
    email: 'djoumessi.w@gmail.com',
    dateInscription: '2024-06-18',
    vues: 167,
    note: 4.6,
    avis: 15,
    tarifJour: 32000,
  },
  {
    nom: 'Nkoa Samuel',
    metier: 'Plombier Sanitaire',
    categorie: 'Artisanat & BTP',
    avatar: 'https://i.pravatar.cc/150?img=37',
    competences: [
      { nom: 'Plomberie', niveau: 93 },
      { nom: 'Sanitaires', niveau: 90 },
      { nom: 'Chauffe-eau', niveau: 85 },
      { nom: 'Détection fuites', niveau: 88 },
    ],
    ville: 'Yaoundé',
    quartier: 'Obili',
    disponibilite: 'disponible',
    bio: "Plombier sanitaire avec 7 ans d'expérience.",
    portfolio: [],
    telephone: '+237 677 890 123',
    email: 'nkoa.samuel@gmail.com',
    dateInscription: '2024-07-01',
    vues: 121,
    note: 4.4,
    avis: 20,
    tarifJour: 16000,
  },
  {
    nom: 'Bika Ornella',
    metier: 'Danseuse & Chorégraphe',
    categorie: 'Créatif & Art',
    avatar: 'https://i.pravatar.cc/150?img=45',
    competences: [
      { nom: 'Danses africaines', niveau: 97 },
      { nom: 'Afrobeats', niveau: 95 },
      { nom: 'Chorégraphie', niveau: 92 },
      { nom: 'Coaching danse', niveau: 88 },
    ],
    ville: 'Douala',
    quartier: 'Bonabéri',
    disponibilite: 'disponible',
    bio: 'Danseuse professionnelle et chorégraphe. Cours de danses africaines et prestations événementielles.',
    portfolio: ['https://picsum.photos/seed/port29/400/300'],
    telephone: '+237 699 901 234',
    email: 'bika.ornella@gmail.com',
    dateInscription: '2024-07-10',
    vues: 245,
    note: 4.8,
    avis: 36,
    tarifJour: 35000,
  },
  {
    nom: 'Happi Romaric',
    metier: 'Data Analyst',
    categorie: 'Tech & Digital',
    avatar: 'https://i.pravatar.cc/150?img=25',
    competences: [
      { nom: 'Python', niveau: 88 },
      { nom: 'Power BI', niveau: 92 },
      { nom: 'Excel avancé', niveau: 94 },
      { nom: 'SQL', niveau: 85 },
    ],
    ville: 'Yaoundé',
    quartier: 'Nlongkak',
    disponibilite: 'disponible',
    bio: "Data analyst avec 3 ans d'expérience. Je transforme vos données en insights actionnables.",
    portfolio: ['https://picsum.photos/seed/port30/400/300'],
    telephone: '+237 655 012 345',
    email: 'happi.romaric@gmail.com',
    dateInscription: '2024-07-22',
    vues: 198,
    note: 4.7,
    avis: 21,
    tarifJour: 28000,
  },
  {
    nom: 'Mouchili Diane',
    metier: 'Coach en Développement Personnel',
    categorie: 'Éducation & Formation',
    avatar: 'https://i.pravatar.cc/150?img=42',
    competences: [
      { nom: 'Coaching', niveau: 93 },
      { nom: 'Prise de parole', niveau: 90 },
      { nom: 'Leadership', niveau: 88 },
      { nom: 'Gestion du temps', niveau: 85 },
    ],
    ville: 'Douala',
    quartier: 'Akwa',
    disponibilite: 'disponible',
    bio: "Coach certifiée ICF. J'accompagne les professionnels et entrepreneurs camerounais.",
    portfolio: [],
    telephone: '+237 677 123 456',
    email: 'mouchili.diane@gmail.com',
    dateInscription: '2024-08-05',
    vues: 287,
    note: 4.9,
    avis: 43,
    tarifJour: 20000,
  },
  {
    nom: 'Zang Pierre',
    metier: 'Ferrailleur & Soudeur',
    categorie: 'Artisanat & BTP',
    avatar: 'https://i.pravatar.cc/150?img=39',
    competences: [
      { nom: 'Soudure MIG/TIG', niveau: 91 },
      { nom: 'Ferraillage', niveau: 88 },
      { nom: 'Portails & grilles', niveau: 94 },
      { nom: 'Métallerie', niveau: 85 },
    ],
    ville: 'Douala',
    quartier: 'PK14',
    disponibilite: 'partiellement disponible',
    bio: "Soudeur-ferrailleur avec 9 ans d'expérience.",
    portfolio: ['https://picsum.photos/seed/port32/400/300'],
    telephone: '+237 690 234 567',
    email: 'zang.pierre@gmail.com',
    dateInscription: '2024-08-15',
    vues: 143,
    note: 4.5,
    avis: 17,
    tarifJour: 18000,
  },
  {
    nom: 'Abena Rosine',
    metier: 'Maquilleuse Professionnelle',
    categorie: 'Services & Lifestyle',
    avatar: 'https://i.pravatar.cc/150?img=40',
    competences: [
      { nom: 'Maquillage mariée', niveau: 96 },
      { nom: 'Maquillage artistique', niveau: 90 },
      { nom: 'Soins peau noire', niveau: 94 },
      { nom: 'Airbrush', niveau: 82 },
    ],
    ville: 'Yaoundé',
    quartier: 'Mendong',
    disponibilite: 'disponible',
    bio: 'Maquilleuse professionnelle spécialisée mariée et événementiel.',
    portfolio: ['https://picsum.photos/seed/port34/400/300'],
    telephone: '+237 655 345 678',
    email: 'abena.rosine@gmail.com',
    dateInscription: '2024-08-25',
    vues: 334,
    note: 4.9,
    avis: 55,
    tarifJour: 25000,
  },
  {
    nom: 'Bello Hamidou',
    metier: 'Livreur Express & Coursier',
    categorie: 'Transport & Logistique',
    avatar: 'https://i.pravatar.cc/150?img=13',
    competences: [
      { nom: 'Livraison urbaine', niveau: 92 },
      { nom: 'Connaissance Douala', niveau: 97 },
      { nom: 'Moto-logistique', niveau: 90 },
      { nom: 'Service client', niveau: 85 },
    ],
    ville: 'Douala',
    quartier: 'Bépanda',
    disponibilite: 'disponible',
    bio: 'Coursier express basé à Douala. Livraison en moins de 2h.',
    portfolio: [],
    telephone: '+237 699 456 789',
    email: 'bello.hamidou@gmail.com',
    dateInscription: '2024-09-03',
    vues: 112,
    note: 4.6,
    avis: 29,
    tarifJour: 8000,
  },
  {
    nom: 'Nganou Cédric',
    metier: 'Technicien Réseau & Cybersécurité',
    categorie: 'Tech & Digital',
    avatar: 'https://i.pravatar.cc/150?img=27',
    competences: [
      { nom: 'Cisco / CCNA', niveau: 88 },
      { nom: 'Cybersécurité', niveau: 82 },
      { nom: 'Administration réseau', niveau: 90 },
      { nom: 'Linux', niveau: 85 },
    ],
    ville: 'Yaoundé',
    quartier: 'Santa Barbara',
    disponibilite: 'occupé',
    bio: 'Technicien réseau certifié CCNA. Expérience en banque et télécoms.',
    portfolio: [],
    telephone: '+237 677 567 890',
    email: 'nganou.cedric@gmail.com',
    dateInscription: '2024-09-12',
    vues: 156,
    note: 4.7,
    avis: 12,
    tarifJour: 30000,
  },
  {
    nom: 'Tsanga Hervé',
    metier: 'Musicien & Arrangeur',
    categorie: 'Créatif & Art',
    avatar: 'https://i.pravatar.cc/150?img=28',
    competences: [
      { nom: 'Guitare', niveau: 95 },
      { nom: 'Arrangement', niveau: 88 },
      { nom: 'Production', niveau: 85 },
      { nom: 'Mixage', niveau: 80 },
    ],
    ville: 'Douala',
    quartier: 'New Bell',
    disponibilite: 'partiellement disponible',
    bio: 'Musicien guitariste et arrangeur. Style : makossa, gospel, afrobeats.',
    portfolio: ['https://picsum.photos/seed/port36/400/300'],
    telephone: '+237 690 678 901',
    email: 'tsanga.herve@gmail.com',
    dateInscription: '2024-09-20',
    vues: 178,
    note: 4.7,
    avis: 24,
    tarifJour: 20000,
  },
  {
    nom: 'Mpeck Fabrice',
    metier: 'Professeur de Langues (Anglais & Français)',
    categorie: 'Éducation & Formation',
    avatar: 'https://i.pravatar.cc/150?img=32',
    competences: [
      { nom: 'Anglais', niveau: 96 },
      { nom: 'Français', niveau: 94 },
      { nom: 'TOEFL / IELTS', niveau: 90 },
      { nom: 'Pédagogie', niveau: 88 },
    ],
    ville: 'Bamenda',
    quartier: 'Up Station',
    disponibilite: 'disponible',
    bio: 'Professeur de langues bilingue. Préparation TOEFL, IELTS, TCF.',
    portfolio: [],
    telephone: '+237 655 789 012',
    email: 'mpeck.fabrice@gmail.com',
    dateInscription: '2024-10-01',
    vues: 201,
    note: 4.8,
    avis: 38,
    tarifJour: 7000,
  },
  {
    nom: 'Essomba Nadège',
    metier: 'Wedding Planner',
    categorie: 'Services & Lifestyle',
    avatar: 'https://i.pravatar.cc/150?img=50',
    competences: [
      { nom: 'Organisation événements', niveau: 94 },
      { nom: 'Décoration', niveau: 90 },
      { nom: 'Coordination', niveau: 92 },
      { nom: 'Budget management', niveau: 85 },
    ],
    ville: 'Douala',
    quartier: 'Bonapriso',
    disponibilite: 'partiellement disponible',
    bio: "Wedding planner avec 5 ans d'expérience. Plus de 60 mariages organisés.",
    portfolio: [
      'https://picsum.photos/seed/port37/400/300',
      'https://picsum.photos/seed/port38/400/300',
    ],
    telephone: '+237 677 890 123',
    email: 'essomba.nadege@gmail.com',
    dateInscription: '2024-10-10',
    vues: 412,
    note: 5,
    avis: 61,
    tarifJour: 80000,
  },
  {
    nom: 'Simo Patrick',
    metier: 'Développeur WordPress & SEO',
    categorie: 'Tech & Digital',
    avatar: 'https://i.pravatar.cc/150?img=14',
    competences: [
      { nom: 'WordPress', niveau: 93 },
      { nom: 'SEO', niveau: 88 },
      { nom: 'PHP', niveau: 78 },
      { nom: 'Google Ads', niveau: 72 },
    ],
    ville: 'Bafoussam',
    quartier: 'Bandjoun',
    disponibilite: 'disponible',
    bio: 'Développeur WordPress et consultant SEO. Plus de 40 sites livrés.',
    portfolio: ['https://picsum.photos/seed/port40/400/300'],
    telephone: '+237 699 901 234',
    email: 'simo.patrick@gmail.com',
    dateInscription: '2024-10-22',
    vues: 223,
    note: 4.6,
    avis: 30,
    tarifJour: 22000,
  },
  {
    nom: 'Onana Gilles',
    metier: 'Peintre en Bâtiment',
    categorie: 'Artisanat & BTP',
    avatar: 'https://i.pravatar.cc/150?img=36',
    competences: [
      { nom: 'Peinture intérieure', niveau: 94 },
      { nom: 'Peinture extérieure', niveau: 90 },
      { nom: 'Décoration murale', niveau: 85 },
      { nom: 'Enduit décoratif', niveau: 82 },
    ],
    ville: 'Douala',
    quartier: 'Yassa',
    disponibilite: 'disponible',
    bio: "Peintre en bâtiment avec 8 ans d'expérience.",
    portfolio: ['https://picsum.photos/seed/port42/400/300'],
    telephone: '+237 655 012 345',
    email: 'onana.gilles@gmail.com',
    dateInscription: '2024-11-01',
    vues: 134,
    note: 4.5,
    avis: 19,
    tarifJour: 14000,
  },
];

const pwdAdmin = 'Admin@2024!';
// ── Compte admin par défaut ───────────────────────────────
const adminSeed = {
  nom: 'Administrateur CamerTalents',
  email: 'admin@camertalents.cm',
  password: pwdAdmin,
  role: 'admin',
  avatar: 'https://i.pravatar.cc/150?img=60',
};

// ── Script principal ──────────────────────────────────────
const seed = async () => {
  try {
    await connectDB();
    console.log('\n🌱 Début du seed...\n');

    // Vide les collections existantes
    await Talent.deleteMany({});
    await User.deleteMany({});
    console.log('🗑️  Collections vidées');

    // Crée le compte admin
    const admin = await User.create(adminSeed);
    console.log(`✅ Admin créé : ${admin.email}`);

    // Crée un User factice pour les talents du seed
    // (en production chaque talent aura son propre compte)
    // const seedUser = await User.create({
    //   nom: 'Seed User',
    //   email: 'seed@camertalents.cm',
    //   password: 'seed_password_123',
    //   role: 'talent',
    // });

    const pwdTalent = 'password123';
    // Crée les 30 profils talents
    let count = 0;
    for (const talentData of talentsSeed) {
      // 1. Créer un user pour ce talent
      const user = await User.create({
        nom: talentData.nom,
        email: talentData.email,
        password: pwdTalent,
        role: 'talent',
      });

      // 2. Créer le talent lié à ce user
      await Talent.create({
        ...talentData,
        userId: user._id,
      });

      count++;
      process.stdout.write(`\r📦 Talents importés : ${count}/${talentsSeed.length}`);
    }
    console.log('🔥 NOUVEAU SEED EN COURS');
    console.log('\n');
    console.log('✅ ════════════════════════════════════════');
    console.log(`   ${count} talents importés avec succès`);
    console.log(`   Admin : admin@camertalents.cm`);
    console.log(`   Mot de passe admin : Admin@2024!`);
    console.log('   ════════════════════════════════════════\n');

    process.exit(0);
  } catch (error) {
    console.error('\n❌ Erreur lors du seed :', error.message);
    process.exit(1);
  }
};

seed();
